In [ ]:
import numpy as np

A = np.array([[1, -1, -1], [1, -1, -1], [1, 1, 1]])
B = np.array([[1, -1, 1], [1, -1, 1], [1, 1, 1]])

w = np.zeros((3, 3))
b = 0

t_A = 1
t_B = -1

print("Initial weights and bias:")
print("Weights:")
print(w)
print("Bias:", b)

for i in range(3):
    for j in range(3):
        w[i, j] += A[i, j] * t_A
    b += t_A

print("Weights for input A:")
print(w)

for i in range(3):
    for j in range(3):
        w[i, j] += B[i, j] * t_B
    b += t_B

print("Weights for input B:")
print(w)

OA = np.sum(A * w) + b
OB = np.sum(B * w) + b

print("Output values for A and B:")
print("Ya:", OA)
print("Yb:", OB)


Initial weights and bias:
Weights:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Bias: 0
Weights for input A:
[[ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1.  1.  1.]]
Weights for input B:
[[ 0.  0. -2.]
 [ 0.  0. -2.]
 [ 0.  0.  0.]]
Output values for A and B:
Ya: 4.0
Yb: -4.0
